services:
  app:
    build: .
    container_name: BANK-GAGAS
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=bank_gagas
      - DB_USERNAME=postgres
      - DB_PASSWORD=123

  postgres:
    image: 'postgres:16-alpine3.21'
    container_name: postgres_db
    environment:
      - 'POSTGRES_DB=bank_gagas'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
